'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34003.
'
Namespace primeRate
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Prime2006WSSoap", [Namespace]:="www.primerateonline.net/FinanceSrvc")>  _
    Partial Public Class Prime2006WS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CalcFinancingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GenAccountNumberOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GenContractOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SaveContractOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LogEventsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.MobileHomeRater.My.MySettings.Default.MobileHomeRater_primeRate_Prime2006WS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CalcFinancingCompleted As CalcFinancingCompletedEventHandler
        
        '''<remarks/>
        Public Event GenAccountNumberCompleted As GenAccountNumberCompletedEventHandler
        
        '''<remarks/>
        Public Event GenContractCompleted As GenContractCompletedEventHandler
        
        '''<remarks/>
        Public Event SaveContractCompleted As SaveContractCompletedEventHandler
        
        '''<remarks/>
        Public Event LogEventsCompleted As LogEventsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.primerateonline.net/FinanceSrvc/CalcFinancing", RequestNamespace:="www.primerateonline.net/FinanceSrvc", ResponseNamespace:="www.primerateonline.net/FinanceSrvc", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CalcFinancing(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String) As TSrvcResponse
            Dim results() As Object = Me.Invoke("CalcFinancing", New Object() {LoginID, LoginPassword, aDoc})
            Return CType(results(0),TSrvcResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CalcFinancingAsync(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String)
            Me.CalcFinancingAsync(LoginID, LoginPassword, aDoc, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CalcFinancingAsync(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String, ByVal userState As Object)
            If (Me.CalcFinancingOperationCompleted Is Nothing) Then
                Me.CalcFinancingOperationCompleted = AddressOf Me.OnCalcFinancingOperationCompleted
            End If
            Me.InvokeAsync("CalcFinancing", New Object() {LoginID, LoginPassword, aDoc}, Me.CalcFinancingOperationCompleted, userState)
        End Sub
        
        Private Sub OnCalcFinancingOperationCompleted(ByVal arg As Object)
            If (Not (Me.CalcFinancingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CalcFinancingCompleted(Me, New CalcFinancingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.primerateonline.net/FinanceSrvc/GenAccountNumber", RequestNamespace:="www.primerateonline.net/FinanceSrvc", ResponseNamespace:="www.primerateonline.net/FinanceSrvc", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GenAccountNumber(ByVal LoginID As String, ByVal LoginPassword As String) As TSrvcResponse
            Dim results() As Object = Me.Invoke("GenAccountNumber", New Object() {LoginID, LoginPassword})
            Return CType(results(0),TSrvcResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GenAccountNumberAsync(ByVal LoginID As String, ByVal LoginPassword As String)
            Me.GenAccountNumberAsync(LoginID, LoginPassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GenAccountNumberAsync(ByVal LoginID As String, ByVal LoginPassword As String, ByVal userState As Object)
            If (Me.GenAccountNumberOperationCompleted Is Nothing) Then
                Me.GenAccountNumberOperationCompleted = AddressOf Me.OnGenAccountNumberOperationCompleted
            End If
            Me.InvokeAsync("GenAccountNumber", New Object() {LoginID, LoginPassword}, Me.GenAccountNumberOperationCompleted, userState)
        End Sub
        
        Private Sub OnGenAccountNumberOperationCompleted(ByVal arg As Object)
            If (Not (Me.GenAccountNumberCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GenAccountNumberCompleted(Me, New GenAccountNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.primerateonline.net/FinanceSrvc/GenContract", RequestNamespace:="www.primerateonline.net/FinanceSrvc", ResponseNamespace:="www.primerateonline.net/FinanceSrvc", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GenContract(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String) As TSrvcResponse
            Dim results() As Object = Me.Invoke("GenContract", New Object() {LoginID, LoginPassword, aDoc})
            Return CType(results(0),TSrvcResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GenContractAsync(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String)
            Me.GenContractAsync(LoginID, LoginPassword, aDoc, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GenContractAsync(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String, ByVal userState As Object)
            If (Me.GenContractOperationCompleted Is Nothing) Then
                Me.GenContractOperationCompleted = AddressOf Me.OnGenContractOperationCompleted
            End If
            Me.InvokeAsync("GenContract", New Object() {LoginID, LoginPassword, aDoc}, Me.GenContractOperationCompleted, userState)
        End Sub
        
        Private Sub OnGenContractOperationCompleted(ByVal arg As Object)
            If (Not (Me.GenContractCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GenContractCompleted(Me, New GenContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.primerateonline.net/FinanceSrvc/SaveContract", RequestNamespace:="www.primerateonline.net/FinanceSrvc", ResponseNamespace:="www.primerateonline.net/FinanceSrvc", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SaveContract(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String) As TSrvcResponse
            Dim results() As Object = Me.Invoke("SaveContract", New Object() {LoginID, LoginPassword, aDoc})
            Return CType(results(0),TSrvcResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SaveContractAsync(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String)
            Me.SaveContractAsync(LoginID, LoginPassword, aDoc, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SaveContractAsync(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String, ByVal userState As Object)
            If (Me.SaveContractOperationCompleted Is Nothing) Then
                Me.SaveContractOperationCompleted = AddressOf Me.OnSaveContractOperationCompleted
            End If
            Me.InvokeAsync("SaveContract", New Object() {LoginID, LoginPassword, aDoc}, Me.SaveContractOperationCompleted, userState)
        End Sub
        
        Private Sub OnSaveContractOperationCompleted(ByVal arg As Object)
            If (Not (Me.SaveContractCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SaveContractCompleted(Me, New SaveContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("www.primerateonline.net/FinanceSrvc/LogEvents", RequestNamespace:="www.primerateonline.net/FinanceSrvc", ResponseNamespace:="www.primerateonline.net/FinanceSrvc", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LogEvents(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String) As TSrvcResponse
            Dim results() As Object = Me.Invoke("LogEvents", New Object() {LoginID, LoginPassword, aDoc})
            Return CType(results(0),TSrvcResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LogEventsAsync(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String)
            Me.LogEventsAsync(LoginID, LoginPassword, aDoc, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LogEventsAsync(ByVal LoginID As String, ByVal LoginPassword As String, ByVal aDoc As String, ByVal userState As Object)
            If (Me.LogEventsOperationCompleted Is Nothing) Then
                Me.LogEventsOperationCompleted = AddressOf Me.OnLogEventsOperationCompleted
            End If
            Me.InvokeAsync("LogEvents", New Object() {LoginID, LoginPassword, aDoc}, Me.LogEventsOperationCompleted, userState)
        End Sub
        
        Private Sub OnLogEventsOperationCompleted(ByVal arg As Object)
            If (Not (Me.LogEventsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LogEventsCompleted(Me, New LogEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.primerateonline.net/FinanceSrvc")>  _
    Partial Public Class TSrvcResponse
        
        Private statusField As TResponseStatus
        
        Private documentField As String
        
        '''<remarks/>
        Public Property Status() As TResponseStatus
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Document() As String
            Get
                Return Me.documentField
            End Get
            Set
                Me.documentField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="www.primerateonline.net/FinanceSrvc")>  _
    Public Enum TResponseStatus
        
        '''<remarks/>
        sOK
        
        '''<remarks/>
        sBusy
        
        '''<remarks/>
        sFailed
        
        '''<remarks/>
        sLoginFailed
        
        '''<remarks/>
        sConnectionFailed
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub CalcFinancingCompletedEventHandler(ByVal sender As Object, ByVal e As CalcFinancingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CalcFinancingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TSrvcResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TSrvcResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub GenAccountNumberCompletedEventHandler(ByVal sender As Object, ByVal e As GenAccountNumberCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GenAccountNumberCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TSrvcResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TSrvcResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub GenContractCompletedEventHandler(ByVal sender As Object, ByVal e As GenContractCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GenContractCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TSrvcResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TSrvcResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub SaveContractCompletedEventHandler(ByVal sender As Object, ByVal e As SaveContractCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SaveContractCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TSrvcResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TSrvcResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")>  _
    Public Delegate Sub LogEventsCompletedEventHandler(ByVal sender As Object, ByVal e As LogEventsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LogEventsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TSrvcResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TSrvcResponse)
            End Get
        End Property
    End Class
End Namespace
